### PR TITLE
Add event submission to the client

### LINKED ISSUE #7: Event Submission API
This is sweet. I didn't see any stuff for submitting events via the event API. Did I miss it? If not, would you be open to a pull request that adds it? They actually support doing it from ruby and it generally Just Works™ if you use the same user agent and remote ip. 

Sorry for opening an issue but I didn't see discussions turned on. Feel free to close this either way.

### PR DESCRIPTION
**Pull request by jnunemaker**
This closes #7. I tried to reduce the blast radius but did have to change some of the existing things to make it work. 

Let me know if you have any problems/changes. I don't get offended. 😄

### CODE REVIEW

**Comment by luctus** [comment]
Thank you very much for this PR, @jnunemaker! It feels so good to receive feedback, comments and actual contributions from someone else :)

I will accept this PR and then will refactor the whole project a bit, to make it super clear that there are 2 "modules": Stats and Events (just like their documentation and API url structure).

**Comment by jnunemaker** [comment]
K. I thought about doing that but didn't want to go too crazy without knowing what you were thinking. 

I love your dailytics project. I've been so close to building it forever. I built gaug.es 15 years ago but we were acquired by GitHub and it's changed hands twice since then. We had email summaries and that was my favorite feature. 

For this project I just want to track when someone signs up (and other things) on flippercloud.io with a custom goal.

**Comment by luctus** [comment]
Oh! Thank you so much for your kind words! Nice to see that your project got acquired, right?

Could you believe me that I checked the flippercloud.io site like 3 days ago??

I will be releasing the new version later today ;)

**Comment by jnunemaker** [comment]
> Nice to see that your project got acquired, right?

Yeah, it was a long time ago (2011). I worked there for ~7 years until MSFT bought them. 

> Could you believe me that I checked the flippercloud.io site like 3 days ago??

Awesome! Happy to answer questions or help if you are curious. Feel free to [email](john@fewerandfaster.com) or [zoom](https://calendly.com/nunemaker/flipper) me.

**Comment by luctus** [comment]
Just published! Thanks a lot for your contribution.

I will come back to you when I have any questions regarding flippercloud ;)

**Pull request merged**
